apiVersion: v1
kind: Secret
metadata:
  name: mariadb-password
type: Opaque
data:
  password: bXltYXJpYWRicGFzc3cwcmQxMjM=
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mdb-pvc
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mdb
  labels:
    app: wordpress
spec:
  ports:
  - port: 3306
  selector:
    app: wordpress
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mdb
  labels:
   app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: mariadb:latest
        name: mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-password
              key: password
        ports:
        - containerPort: 3306
          name: mariadb
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mdb-volume
      volumes:
      - name: mdb-volume
        persistentVolumeClaim:
          claimName: mdb-pvc