apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: wordpress