apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-vol-claim
spec:
#  storageClassName: default #Uncomment for non default storage class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debian-dep
  labels:
    app: my-debian-app
  annotations:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-debian-app
  template:
    metadata:
      labels:
        app: my-debian-app
    spec:
      containers:
        - name: debian
          image: debian:stable
          command: ["/usr/bin/tail","-f","/dev/null"]
          volumeMounts:
          - mountPath: "/var/pv_path"
            name: external
      volumes:
        - name: external
          persistentVolumeClaim:
            claimName: my-vol-claim
